# A generic, single-database configuration for Alembic.

[alembic]
# path to migration script directory
script_location = migrations

# template used to generate migration file names
file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
prepend_sys_path = .

# timezone to use when rendering dates in migration files
timezone = UTC

# max length of characters which # are used to render the --autogenerate title
truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a corresponding .py file to be detected as revisions
sourceless = false

# version location specification; This defaults
# to migrations/versions. When using multiple version
# directories, initial revisions must be created with --version-path.
version_locations = %(here)s/migrations/versions

# set to 'true' to search source files recursively
recursive_version_locations = false

# sqlalchemy.url is dynamically populated in migrations/env.py from DATABASE_URL
sqlalchemy.url = postgresql://postgres:postgres@localhost:5432/worklog

[post_write_hooks]

[logging]
default_handler = console

[loggers]
keys = root,alembic,sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_alembic]
level = INFO
handlers = console
qualname = alembic

[logger_sqlalchemy]
level = WARN
handlers = console
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
